workspace 'BlogMap_Philly'
platform :ios,'8.0'
pod 'AFNetworking', '~> 1.3.4'
pod 'CCHLinkTextView'
pod 'CCHMapClusterController'
pod 'CCHMapsActivity'
pod 'GoogleAnalytics-iOS-SDK'
pod 'OCMock'
pod 'TUSafariActivity'
pod 'MBXMapKit'
